# FABER Software Development Workflow
# This example demonstrates the YAML workflow definition format
# Usage: faber run 123 --workflow software-dev.yaml

name: software-dev
version: "1.0"
description: |
  Standard software development workflow implementing the 5-phase
  FABER methodology: Frame, Architect, Build, Evaluate, Release.

triggers:
  - type: manual
    command: /faber
  - type: issue_labeled
    labels:
      - faber-ready

config:
  work_platform: github
  repo_platform: github
  autonomy: assisted
  max_retries: 3

models:
  default: anthropic:claude-sonnet-4-20250514
  classification: anthropic:claude-3-5-haiku-20241022
  reasoning: anthropic:claude-sonnet-4-20250514
  review: anthropic:claude-sonnet-4-20250514

phases:
  - name: frame
    description: Gather requirements and classify work type
    agent: frame-agent
    model: $models.classification
    tools:
      - fetch_issue
      - classify_work_type
      - log_phase_start
      - log_phase_end
    outputs:
      - issue
      - work_type
      - requirements
    max_iterations: 20

  - name: architect
    description: Create detailed technical specification
    agent: architect-agent
    model: $models.reasoning
    tools:
      - create_specification
      - validate_specification
      - get_refinement_questions
      - log_info
    inputs:
      - $frame.issue
      - $frame.work_type
      - $frame.requirements
    outputs:
      - specification
      - spec_path
    human_approval: true
    approval_prompt: |
      Please review the specification for work item #{work_id}.

      Specification path: {spec_path}

      Reply 'approve' to continue or provide feedback for revisions.
    max_iterations: 50

  - name: build
    description: Implement the solution according to specification
    agent: build-agent
    model: $models.default
    tools:
      - get_specification
      - create_branch
      - generate_branch_name
      - git_commit
      - log_info
    inputs:
      - $architect.specification
      - $architect.spec_path
    outputs:
      - branch_name
      - commits
      - implementation_summary
    max_iterations: 100

  - name: evaluate
    description: Validate implementation against specification
    agent: evaluate-agent
    model: $models.review
    tools:
      - get_specification
      - validate_specification
      - log_info
      - log_error
    inputs:
      - $architect.specification
      - $build.branch_name
      - $build.implementation_summary
    outputs:
      - evaluation_result
      - evaluation_feedback
    on_failure:
      retry_phase: build
      max_retries: $config.max_retries
    max_iterations: 50

  - name: release
    description: Create PR and deliver the solution
    agent: release-agent
    model: $models.classification
    tools:
      - git_push
      - create_pull_request
      - create_issue_comment
      - log_phase_end
    inputs:
      - $build.branch_name
      - $evaluate.evaluation_result
    outputs:
      - pr_url
      - pr_number
    human_approval: true
    approval_prompt: |
      Ready to create PR for work item #{work_id}.

      Branch: {branch_name}
      Evaluation: {evaluation_result}

      Reply 'approve' to create the PR or 'cancel' to abort.
    max_iterations: 20

hooks:
  on_complete:
    - action: comment_issue
      message: |
        FABER workflow completed successfully!

        PR: {pr_url}
        Branch: {branch_name}
    - action: notify
      channel: slack
      message: "FABER completed #{work_id} - PR ready for review"

  on_failure:
    - action: comment_issue
      message: |
        FABER workflow failed at phase: {error_phase}

        Error: {error}

        Please review and retry.
    - action: notify
      channel: slack
      message: "FABER failed #{work_id} at {error_phase}"
